source 'https://rubygems.org'

gem 'excon'
gem 'platform-api'
gem 'pry'
gem 'git'
gem 'activesupport', require: 'active_support/all'
gem 'parallel'
gem 'sinatra', require: 'sinatra/base'
gem 'puma'
gem 'fast_secure_compare'
