source 'https://rubygems.org'

gem 'dotenv', require: 'dotenv/load'
gem 'fast_blank'
gem 'excon'
gem 'platform-api'
gem 'pry'
gem 'git'
gem 'activesupport', require: 'active_support/all'
gem 'json'
gem 'rspec'
gem 'parallel'
